# Generated by Django 2.2.3 on 2019-07-10 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Torrent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('torrent_hash', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=500)),
                ('download_dir', models.CharField(max_length=500)),
                ('is_episode', models.BooleanField(default=False)),
                ('episode_num', models.PositiveSmallIntegerField(null=True)),
                ('season', models.PositiveSmallIntegerField(null=True)),
                ('torrent_file', models.IntegerField()),
                ('torrent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mytube.Torrent')),
            ],
        ),
    ]
